<?php
/**
 * Integrates Magento with the custom price calculator based on user input on product view page.
 *
 * @author Bhavin Shah
 * @copyright Copyright (c) 2021 Bhavin (https://bhavin-shah.com)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Catalog\Block\Product\View $block */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<?php if ($_product->getEnableCalculator()): ?>
<div class="calculator-note">
    <label><?php /* @escapeNotVerified */ echo __('Note:'); ?></label>
    <div class="note"><?php /* @escapeNotVerified */ echo __('Price is based on per square feet'); ?></div>
</div>
<?php endif; ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty'); ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1; ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty'); ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>"
                       />
            </div>
        </div>
        <!-- Custom Input Fields -->
        <?php if ($_product->getEnableCalculator()): ?>
        <div class="field ">
            <label class="label" for="height">
                <span><?php /* @escapeNotVerified */ echo __('Height'); ?><em>*</em></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    name="calculator[height]"
                    id="height"
                    class="validate-number required-entry validate-greater-than-zero"
                    placeholder="Enter height in feet"
                />
            </div>
        </div>
        <div class="field ">
            <label class="label" for="width">
                <span><?php /* @escapeNotVerified */ echo __('Width'); ?><em>*</em></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    name="calculator[width]"
                    id="width"
                    class="validate-number required-entry validate-greater-than-zero"
                    placeholder="Enter width in feet"
                />
            </div>
        </div>
        <?php endif; ?>
        <!-- Custom Input Fields -->
        <br>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle; ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle; ?></span>
            </button>
            <?php echo $block->getChildHtml('', true); ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
